# Generated by Django 6.0.3 on 2026-10-03 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquawatch_app', '0003_device_capabilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('gyro_x', models.CharField(blank=True, max_length=64)),
                ('gyro_y', models.CharField(blank=True, max_length=64)),
                ('gsm_signal', models.CharField(blank=True, max_length=128)),
                ('acceleration', models.CharField(blank=True, max_length=128)),
                ('water_level_value', models.CharField(blank=True, max_length=128)),
                ('is_distress', models.BooleanField(default=False)),
                ('alert_type', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='MobileAuthWindow',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileToken',
            fields=[
                ('digest', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('password_signature', models.CharField(max_length=64)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SignupChallenge',
            fields=[
                ('email', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('code_digest', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SyncReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128)),
                ('payload_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='source_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='device',
            name='last_status_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='mobile_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='mobile_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('user', 'mobile_id'), name='device_user_mobile_id'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('user', 'mobile_id'), name='report_user_mobile_id'),
        ),
        migrations.AddField(
            model_name='devicereading',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='aquawatch_app.device'),
        ),
        migrations.AddField(
            model_name='mobiletoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='syncreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='devicereading',
            index=models.Index(fields=['device', '-received_at'], name='reading_device_time'),
        ),
        migrations.AddConstraint(
            model_name='syncreceipt',
            constraint=models.UniqueConstraint(fields=('user', 'event_id'), name='sync_user_event_id'),
        ),
    ]
